{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "football-lesson-generator.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "football-lesson-generator.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.serviceType }}
  selector:
    app.kubernetes.io/name: {{ include "football-lesson-generator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
{{- end }}
