namespace: ea

image:
  repository: registry.ea.com/football-lesson-gen  # <- CHANGE to your registry
  tag: latest
  pullPolicy: IfNotPresent

schedule: "0 3 * * 1"  # every Monday at 03:00

confluence:
  baseUrl: "https://confluence.ea.com"
  parentPageId: "1329880121"
  # These should be set via --set or in a separate values file, not committed
  user: ""      # e.g. sfiore@ea.com
  password: ""  # e.g. PAT or password

google:
  spreadsheetId: "1yxEJJG4vU9oc7Yed2OPsLRyulO36UiLDrJ1xUthCTYM"
  sheetGid: "0"
  saJsonPath: "/secrets/service-account.json"
  saSecretName: "google-service-account"  # pre-created Secret with service-account.json key

ollama:
  apiUrl: "https://thehive.tib.ad.ea.com/api/generate" #need to update using for MCP
  model: "codellama:7b"

env:
  debug: "0"

serviceAccount:
  create: true
  name: ""  # if empty, fullname + "-sa" will be used

resources: {}
  # requests:
  #   cpu: "250m"
  #   memory: "512Mi"
  # limits:
  #   cpu: "1"
  #   memory: "1Gi"

nodeSelector: {}
tolerations: []
affinity: {}
