image:
  repository: sfiore915/sheet-to-confluence
  tag: latest
  pullPolicy: IfNotPresent

schedule: "0 3 * * 1"

confluence:
  baseUrl: "https://confluence.ea.com"
  pageId: "1329880121"
  existingSecretName: "football-lesson-generator-confluence"

attachment:
  filename: "football-course-outline.csv"

google:
  spreadsheetId: "1yxEJJG4vU9oc7Yed2OPsLRyulO36UiLDrJ1xUthCTYM"
  sheetGid: ""
  saSecretName: "google-service-account"
  saSecretKey: "service-account.json"
  saMountPath: "/secrets/service-account.json"

source:
  kind: "sheet_values"
  render: "FORMATTED_VALUE"
  sheetTabName: "Curriculum"

writeBack:
  range: ""
  template: "Last sync: {timestamp} | File: {filename} | Status: {status}"
  appendLog: ""

ollama:
  apiUrl: "http://ollama:11434/api/generate"
  model: "llama3.2:1b"

env:
  debug: "0"

serviceAccount:
  create: true
  name: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
imagePullSecrets: []

api:
  enabled: true
  port: 9101
  serviceType: ClusterIP
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    tls: []
